# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: WebpageTesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install Playwright
      run: npm install @playwright/test

    - name: Install Playwright Dependencies
      run: npx playwright install-deps
      
    - name: Install dependencies
      run: dotnet restore EpamWebTests/EpamWebTests.sln

    - name: Install Playwright Browsers
      run: npx playwright install
      
    - name: Build the project
      run: dotnet build EpamWebTests/EpamWebTests.sln --no-restore
          
    - name: Run Playwright Tests
      run: dotnet test EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity normal
      

