name: WebpageTesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      category:
        description: 'Test category to run'
        required: false
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Playwright
      run: npm install @playwright/test

    - name: Install Playwright Dependencies
      run: npx playwright install-deps

    - name: Install dependencies
      run: dotnet restore EpamWebProject/EpamWebTests/EpamWebTests.sln

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Verify Allure Results Directory
      run: |
        if [ -d allure-results ]; then
          echo "Allure results directory exists"
        else
          echo "Allure results directory does not exist, creating it now."
          mkdir -p allure-results allure-history
        fi

    - name: Build the project
      run: dotnet build EpamWebProject/EpamWebTests/EpamWebTests.sln --no-restore

    - name: Run Playwright Tests
      run: |
        if [ "${{ github.event.inputs.category }}" == "all" ] || [ -z "${{ github.event.inputs.category }}" ]; then
          dotnet test EpamWebProject/EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ${{ github.workspace }}/allure-results
        else
          dotnet test EpamWebProject/EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ${{ github.workspace }}/allure-results --filter "Category=${{ github.event.inputs.category }}"
        fi

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Build and Publish Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Publish Allure Test Report
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
