# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: WebpageTesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install Playwright
      run: npm install @playwright/test

    - name: Install Playwright Dependencies
      run: npx playwright install-deps
      
    - name: Install dependencies
      run: dotnet restore EpamWebTests/EpamWebTests.sln

    - name: Install Playwright Browsers
      run: npx playwright install
      
    - name: Build the project
      run: dotnet build EpamWebTests/EpamWebTests.sln --no-restore
          
    - name: Run Playwright Tests
      run: dotnet test EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity normal --logger:"nunit;LogFilePath=./allure-results"

    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    # Publish Allure Report
    - name: Build and Publish Allure Report
      uses: simple-elf/allure-report-action@1.1
      if: always()
      with:
        allure_results: ./allure-results  # Path where Allure results are stored
        gh_pages: gh-pages
        allure_history: allure-history
        keep_reports: 20

    # Publish test report to GitHub Pages
    - name: Publish Allure Test Report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

