# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: WebpageTesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # Step 4: Install Playwright package
    - name: Install Playwright
      run: npm install @playwright/test

    # Step 5: Install all required libraries using Playwright script
    - name: Install Playwright Dependencies
      run: npx playwright install-deps
      
    - name: Restore dependencies
      run: dotnet restore EpamWebTests/EpamWebTests.sln
      
    # Step 8: Build the project
    - name: Build the project
      run: dotnet build EpamWebTests/EpamWebTests.sln --no-restore

    # Step 7: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install

      
    - name: Clean build artifacts
      run: dotnet clean EpamWebTests/EpamWebTests.csproj

    - name: Run Playwright Tests
      run: dotnet test EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity detailed --no-build --logger "trx;LogFileName=TestResults.trx"

    - name: List files in output directory
      run: ls -R EpamWebTests/bin/Release/net8.0/
      
    # Step 9: Run Playwright Tests
    - name: Run Playwright Tests
      run: dotnet test EpamWebTests/EpamWebTests.csproj --configuration Release --no-build --verbosity normal
      

